### ISSUE TITLE
Unable to locate your dataset

### ISSUE THREAD

**Issue by jsinghh09** [PrateekDutta2001/Oral-Cancer-Detection#1]
Hi can you share your dataset. I am interested in learning more about it

**Comment by sachin-source** [comment]
I'm not able to get the dataset provided from the link..
Can you please share the dataset?

**Comment by Obaid-Ullah** [comment]
Unable to identify your dataset

**Comment by fatmaahmed2500** [comment]
hello can u share your dataset i need it badly ?

**Comment by PrateekDutta2001** [comment]
> Hi can you share your dataset. I am interested in learning more about it

Hey, Thanks for reaching out to me!
You can access the dataset from here: https://drive.google.com/file/d/1Fsopa1YvQPqwde7xxLvprGqRuvEXXvNo/view?usp=sharing

Thanks

**Comment by PrateekDutta2001** [comment]
> Unable to identify your dataset

Hey, Thanks for reaching out to me!
You can access the dataset from here: https://drive.google.com/file/d/1Fsopa1YvQPqwde7xxLvprGqRuvEXXvNo/view?usp=sharing

Thanks

**Comment by PrateekDutta2001** [comment]
> hello can u share your dataset i need it badly ?

Hey, Thanks for reaching out to me!
You can access the dataset from here: https://drive.google.com/file/d/1Fsopa1YvQPqwde7xxLvprGqRuvEXXvNo/view?usp=sharing

Thanks

**Comment by PrateekDutta2001** [comment]
> I'm not able to get the dataset provided from the link.. Can you please share the dataset?

Hey, Thanks for reaching out to me!
You can access the dataset from here: https://drive.google.com/file/d/1Fsopa1YvQPqwde7xxLvprGqRuvEXXvNo/view?usp=sharing

Thanks

**Comment by fatmaahmed2500** [comment]
> > I'm not able to get the dataset provided from the link.. Can you please share the dataset?
> 
> Hey, Thanks for reaching out to me! You can access the dataset from here: https://drive.google.com/file/d/1Fsopa1YvQPqwde7xxLvprGqRuvEXXvNo/view?usp=sharing
> 
> Thanks

thanks it was very helpful
